### ISSUE TITLE
Add exporters to provide CSV data so that the resulting analytics data can be used to produce other custom analytics.

### ISSUE THREAD

**Issue by rchakode** [rchakode/kube-opex-analytics#4]

**Comment by ccamel** [comment]
Hi :smiley: 

How do you think the feature should be implemented?

Do you consider to write csv files alongside the json files?

**Comment by rchakode** [comment]
Hello :),
I was thinking of something like a download button to get the data as CSV file.
What is your feelings about this?

**Comment by ccamel** [comment]
Yes, agree with that.

I was just wondering if export process should take place in the backend side or in the frontend side.

PS: I can contribute to this one once we've agreed on the implementation. :relieved:

**Comment by rchakode** [comment]
Yo,
Nice to hear this, thank you in advance for your contributions. 

Regarding the approach of implementation, I've not strong opinion to choose one of the approaches. 
So perhaps I will leave you choose the one that you think is better and/or that you're comfortable with. Just let's know.

**Comment by ccamel** [comment]
@rchakode after consideration, I think the most suitable approach would be to have the export implemented on the front only. We can do alsmost anything we want, and it's far simpler.

If you don't mind, I can start working on it.

**Comment by rchakode** [comment]
@ccamel, let's move on this way. 
I agree that the front-end approach is more flexible.

**Comment by rchakode** [comment]
@ccamel if you ever want help to understand how things are designed in the back or the front side, just let me know.

**Comment by ccamel** [comment]
@rchakode I had time to start working on the feature. Preliminary work is available on branch [ccamel:export-csv](https://github.com/rchakode/kube-opex-analytics/compare/master...ccamel:export-csv).

At the time of writting, the implementation covers the export of the first 6 datasets (Last week hourly cpu and memory usage trends, two-weeks daily cpu and memory usage and one-year monthly cpu and memory usage) in both `json` and `csv` format.

Regarding the UI, data export is available via a muted/subtle dropdown button displaying the list of data format (json, csv).

Before going further, I would like to have your opinion on the direction taken so that I can adjust if necessary. :relaxed: 

Thx.

**Comment by rchakode** [comment]
@ccamel,
Thank you, let me checking it out and try it.
I'll let you know when this is done.

**Comment by rchakode** [comment]
@ccamel I deployed that version. 
The way you introduced the download button looks really cool, it's also interesting the fact to have also introduced an option to download a JSON version.
I'm waiting to get more data to test again the download. 
So far everything is going well :+1:

**Comment by rchakode** [comment]
@ccamel after additional tests, everything looks okay. 
You can submit the PR so I can merge it.
During the merge I'll also update the documentation to describe the introduced features :)
